"""Added severity column to PollutionReport

Revision ID: a3ee10cbd34b
Revises: 
Create Date: 2025-02-24 23:47:53.195281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ee10cbd34b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pollution_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pollution_report', schema=None) as batch_op:
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
